# Generated by Django 3.2 on 2021-11-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_to',
            field=models.TimeField(),
        ),
    ]
